config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :articles

  resources :articles do
    resources :comments
  end
  resources :demo
  # get 'demo/data'
  # root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :name, presence: true,
                    length: { minimum: 5 }
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :students
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "atul", password: "secret", except: [:index, :show]

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def index
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    # render plain: params[:article].inspect
    # @article = Article.new(params[:article])
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:name, :age)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "atul", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def data

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

<% if @article.errors.any? %>
  <div id="error explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %>
      found
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <%= link_to 'Back', articles_path %>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
  </tr>

  <% @article.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= article.age %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @article.age %>
</p>

<h2>Comments</h2>

<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/demo/data.html.erb
<h1>Demo Controller</h1>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= "count to 10" %>
</br>
<% 11.times do |i| %>
  <%= i %>
<% end %>